#!/bin/bash -xe
sudo apt update
sudo apt install -y nfs-common ansible unzip curl snapd
ansible --version
sudo mkdir share
sudo chmod -R 777 share
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-02995a7b915f6a691.efs.us-east-1.amazonaws.com:/ share
sudo snap install amazon-ssm-agent --classic
sudo systemctl enable --now snap.amazon-ssm-agent.amazon-ssm-agent.service
sudo systemctl status snap.amazon-ssm-agent.amazon-ssm-agent.service
openssl rand -base64 16
